default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: elm_supported_rails_development
test:
  <<: *default
  database: elm_supported_rails_test
